# Generated by Django 2.2.3 on 2019-07-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zz_500s',
            name='close',
        ),
        migrations.AddField(
            model_name='zz_500s',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
