# Generated by Django 2.2.3 on 2019-07-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190708_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='zz_500s',
            name='asset_varity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo.ASSET_VARITY'),
        ),
    ]
