# Generated by Django 2.2.3 on 2019-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_remove_asset_varity_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_varity',
            name='cap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
