# Generated by Django 2.2.3 on 2019-07-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_asset_varity_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_varity',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varity_type', to='demo.ASSET_TYPE'),
        ),
    ]
